name: Deploy KING-SANDESH-MD Bot

on:
  push:
    branches:
      - V-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🔨 Build Project (if needed)
        run: |
          if [ -f package.json ] && grep -q '"build"' package.json; then
            npm run build
          else
            echo "No build step found."
          fi

      - name: 🚀 Start Bot with PM2
        run: |
          npm install -g pm2
          pm2 start index.js --name KING-SANDESH-MD || pm2 restart KING-SANDESH-MD
